name: Build

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip -q install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip -q install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Database download 
      run: |
        wget -q ${{ secrets. SOURCE_DATABASE }}
        unzip IP2PROXY-LITE-PX1.BIN.ZIP -x *.TXT
        mv IP2PROXY-LITE-PX1.BIN proxydetectorfirewall/data/

    - name: Test with pytest
      run: |
        pip -q install pytest
        pytest tests/output_files_test.py